namespace HubSpot.NET.Models
{
    public enum AssociationTypeId
    {
        // Company-to-Object associations
        CompanyToCompany = 450,
        ChildToParentCompany = 14,
        ParentToChildCompany = 13,
        CompanyToContact = 280,
        CompanyToContactPrimary = 2,
        CompanyToDeal = 342,
        CompanyToDealPrimary = 6,
        CompanyToTicket = 340,
        CompanyToTicketPrimary = 25,
        CompanyToCall = 181,
        CompanyToEmail = 185,
        CompanyToMeeting = 187,
        CompanyToNote = 189,
        CompanyToTask = 191,
        CompanyToCommunication = 88, // SMS, WhatsApp, or LinkedIn message
        CompanyToPostalMail = 460,
        CompanyToInvoice = 180,
        CompanyToOrder = 510,
        CompanyToPayment = 390,
        CompanyToPaymentLink = 472,
        CompanyToSubscription = 298,
        CompanyToAppointment = 909,
        CompanyToCourse = 939,
        CompanyToListing = 885,
        CompanyToService = 793,
        CompanyToFeedbackSubmission = 929,
        // Contact-to-Object associations
        ContactToContact = 449,
        ContactToCompany = 279,
        ContactToCompanyPrimary = 1,
        ContactToDeal = 4,
        ContactToTicket = 15,
        ContactToCall = 193,
        ContactToEmail = 197,
        ContactToMeeting = 199,
        ContactToNote = 201,
        ContactToTask = 203,
        ContactToCommunication = 82, // SMS, WhatsApp, or LinkedIn message
        ContactToPostalMail = 454,
        ContactToCart = 587,
        ContactToOrder = 508,
        ContactToInvoice = 178,
        ContactToPayment = 388,
        ContactToPaymentLink = 470,
        ContactToSubscription = 296,
        ContactToAppointment = 907,
        ContactToCourse = 861,
        ContactToListing = 883,
        ContactToService = 799,
        ContactToFeedbackSubmission = 97,
        // Email-to-Object associations
        EmailToContact = 198,
        EmailToCompany = 186,
        EmailToDeal = 210,
        EmailToTicket = 224,
        EmailToAppointment = 917,
        EmailToCourse = 871,
        EmailToListing = 895,
        EmailToService = 843,
        // Cart-to-Object associations
        CartToContact = 586,
        CartToLineItem = 590,
        CartToOrder = 592,
        CartToTask = 728,
        // Order-to-Object associations
        OrderToCart = 593,
        OrderToContact = 507,
        OrderToCompany = 509,
        OrderToLineItem = 513,
        OrderToPayment = 523,
        OrderToTask = 726,
    }
}
